Repository Full-Tortuga/decide-full-tortuga-admin, pull requests merged in 2022-01, with the labels that each got.

#58 Feature/#13 votings api
  decide/administration/serializers.py
  decide/administration/urls.py
  decide/administration/views.py
Labels: backend

#61 Feature/#13 votings api - Put endpoint
  decide/administration/views.py
Labels: enhancement, refactor

#73 #70-fix: Only superusers can login now in administration view
  decide/administration/views.py
Labels: bug
